TABLA_SUBASTA_DIVISA_HIST

DROP TABLE BDVNET.SUBASTA_DIVISA_HIST CASCADE CONSTRAINTS;

CREATE TABLE BDVNET.SUBASTA_DIVISA_HIST
(
  NRO_CORRELATIVO            NUMBER             NOT NULL,
  FECHA_SUBASTA              DATE               NOT NULL,
  CODIGO_SUBASTA             VARCHAR2(7 BYTE)   NOT NULL,
  CODIGO_OPERADOR_CAMBIARIO  VARCHAR2(3 BYTE)   NOT NULL,
  NOMBRE_OPERADOR_CAMBIARIO  VARCHAR2(100 BYTE),
  FECHA_VALOR                DATE,
  RIF                        VARCHAR2(20 BYTE)  NOT NULL,
  RAZON_SOCIAL               VARCHAR2(200 BYTE),
  CODIGO_MONEDA              VARCHAR2(3 BYTE),
  MONTO_USD                  NUMBER(19,2),
  TIPO_CAMBIO_BS_USD         NUMBER(19,2),
  CONTRAVALOR_BS             NUMBER(19,2),
  CUENTA_MONEDA_NACIONAL     VARCHAR2(20 BYTE),
  NUMERO_RETENCION           VARCHAR2(50 BYTE),
  STATUS                     VARCHAR2(1 BYTE),
  CUENTA_MONEDA_EXTRANJERA   VARCHAR2(20 BYTE)  NOT NULL,
  CEDULA                     VARCHAR2(12 BYTE),
  FECHA_MIGRACION            DATE               DEFAULT SYSDATE
)
TABLESPACE DATA_BDVNETP
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
COMPRESS BASIC
NOCACHE;


CREATE INDEX BDVNET.IDX_HIST_FECH_MIGR ON BDVNET.SUBASTA_DIVISA_HIST
(FECHA_MIGRACION)
LOGGING
TABLESPACE DATA_BDVNETP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BDVNET.IDX_HIST_RIF_SUB ON BDVNET.SUBASTA_DIVISA_HIST
(RIF, CODIGO_SUBASTA)
LOGGING
TABLESPACE DATA_BDVNETP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
