ESQUEMAS CYCLOPSQ 



- FINANCIAL_CORE

CREATE TABLESPACE DATA_FINANCIAL_CORE
DATAFILE 
  '+DATA_CYC' SIZE 1024M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE INDX_FINANCIAL_CORE
DATAFILE 
  '+DATA_CYC' SIZE 1024M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


- BIOPOS

--  DEFAULT TABLESPACE BIOPOS (PRODUCCION)

CREATE TABLESPACE DATA_BIOPOS
DATAFILE 
  '+DATA_CYC' SIZE 1024M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE INDX_BIOPOS
DATAFILE 
  '+DATA_CYC' SIZE 1024M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;




ESQUEMAS IDENTTYQ 
     - CYCLOPS_IDENTITY_BIOPOS
 -- DEFAULT TABLESPACE BIOPOS (PRODUCCION)
CREATE TABLESPACE DATA_CYCLOPS_IDENTITY_BIOPOS
DATAFILE 
  '+DATA_IDENT' SIZE 1024M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED
LOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE INDX_CYCLOPS_IDENTITY_BIOPOS
DATAFILE 
  '+DATA_IDENT' SIZE 1024M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED
LOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;