-- DROP TABLE PCPH.DEBITS_HIST CASCADE CONSTRAINTS;

CREATE TABLE PCPH.DEBITS_HIST
(
  ID_DEBITS                  NUMBER(18)         NOT NULL,
  ID_ORDEN                   NUMBER(30),
  REFERENCE_NUMBER           NUMBER(20),
  CUSTOMER_ID                VARCHAR2(20 BYTE),
  RECORD_ENTRY_DATE          DATE,
  CUSTOMER_DESC              VARCHAR2(256 BYTE),
  PROCESS_DATE               DATE,
  ACCOUNT_NUMBER             VARCHAR2(20 BYTE),
  ACCOUNT_TYPE               VARCHAR2(3 BYTE),
  AMOUNT                     NUMBER(20,2),
  CURRENCY                   VARCHAR2(3 BYTE),
  PAYMENT_TYPE               VARCHAR2(3 BYTE),
  IS_PAYROLL                 VARCHAR2(1 BYTE),
  STATUS                     NUMBER(2),
  BUSINESS_STATUS_CODE       VARCHAR2(8 BYTE),
  MONTO_ACTUALIZADO          NUMBER(20,2),
  VERIFICACION_SALDO         VARCHAR2(2 BYTE),
  ID_DEBITS_ROOT             NUMBER(18),
  RETRY                      NUMBER(4),
  BUSINESS_STATUS_DESC       VARCHAR2(100 BYTE),
  ID_CREDITS_REVERSO         NUMBER(18),
  TOTAL_CREDITOS_RECHAZADOS  NUMBER(20),
  TOTAL_CREDITOS_ACEPTADOS   NUMBER(15),
  PAGO_POSTERIOR             VARCHAR2(1 BYTE),
  SERIAL                     VARCHAR2(20 BYTE),
  ES_TRANSPORT               VARCHAR2(1 BYTE),
  STATUS_COMIS_TRANSPORT     NUMBER(2),
  COD_MENSAJE_OPS            VARCHAR2(6 BYTE),
  OPS                        VARCHAR2(20 BYTE),
  DATE_UPDATE                DATE,
  STATUS_PATRIA              VARCHAR2(1 BYTE),
  ES_ACTULIZADO              VARCHAR2(1 BYTE)
)
NOCOMPRESS 
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (PROCESS_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(  
  PARTITION P_INITIAL VALUES LESS THAN (TO_DATE(' 2018-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE;
