CREATE TABLE PCP.MIGRATION_WEEK_LOG
(
  LOG_ID              NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
  FECHA_INICIO        TIMESTAMP(6),
  FECHA_FIN           TIMESTAMP(6),
  SEMANA_INICIO       DATE,
  SEMANA_FIN          DATE,
  ORDENES_OK          NUMBER,
  ORDENES_ERROR       NUMBER,
  DEBITS              NUMBER,
  CREDITS             NUMBER,
  CREDITS_INM         NUMBER,
  DATOS_MOV           NUMBER,
  NUM_LOGS            NUMBER,
  NUM_DETAILS         NUMBER,
  TOTAL_CREDITOS      NUMBER,
  TIEMPO_POR_CREDITO  NUMBER,
  SEGUNDOS_TOTAL      NUMBER,
  ESTADO              VARCHAR2(20 BYTE),
  MENSAJE_ERROR       VARCHAR2(4000 BYTE),
  T_ORDEN_SEG         NUMBER,
  T_DEBITS_SEG        NUMBER,
  T_CREDITS_SEG       NUMBER,
  T_CREDITS_INM_SEG   NUMBER,
  T_DATOS_MOV_SEG     NUMBER,
  T_LOGS_SEG          NUMBER,
  T_DETAILS_SEG       NUMBER
)

