-- Eliminar la tabla si existe (opcional, para pruebas)
-- DROP TABLE PCP.TORDEN_HIST CASCADE CONSTRAINTS PURGE;

CREATE TABLE PCP.TORDEN_HIST
(
  ID_TORDEN               NUMBER(18) NOT NULL,
  CUSTOMER_DESCRIPTION    VARCHAR2(150 BYTE),
  ACCOUNT_NUMBER          VARCHAR2(20 BYTE),
  DATE_VALUE              DATE,
  TOTAL_AMOUNT            NUMBER(20,2),
  TOTAL_COMISSION         NUMBER(20,2),
  CENTRO_OPER             VARCHAR2(5 BYTE)      DEFAULT '03291',
  CUSTOMER_ID             VARCHAR2(20 BYTE),
  DIG_CUSTOMER_ID         NUMBER(1),
  TOTAL_NUM_RECORD        NUMBER(12),
  TIPO_NOMINA             VARCHAR2(1 BYTE),
  CODIGO_PLAN             VARCHAR2(8 BYTE),
  FECHA_PROCESO           VARCHAR2(10 BYTE),
  HORA_PROCESO            VARCHAR2(8 BYTE),
  NOM_ARCHIVO             VARCHAR2(255 BYTE),
  NUMERO_TICKET           VARCHAR2(20 BYTE),
  NUMERO_ASIGNADO_PAMPA   NUMBER(18),
  RECORD_ENTRY_DATE       TIMESTAMP(6)          DEFAULT SYSTIMESTAMP,
  PRODUCT_TYPE            VARCHAR2(8 BYTE),
  PRODUCT                 VARCHAR2(8 BYTE),
  COD_RETORNO_PAMPA       VARCHAR2(2 BYTE),
  STATUS                  NUMBER(2),
  BUSINESS_STATUS_CODE    VARCHAR2(2 BYTE),
  TOTAL_OK                NUMBER(20),
  TOTAL_REJECTS           NUMBER(20),
  TOTAL_AMOUNT_REJECTS    NUMBER(20,2),
  DATE_APPROVE            TIMESTAMP(6),
  URI_FILE                VARCHAR2(220 BYTE),
  SIZE_FILE               NUMBER(10),
  SUBCHANNEL              NUMBER(1),
  SENT_DATE               DATE,
  SEND_CHANNEL            NUMBER(2),
  REQUEST_DATE            DATE,
  LAST_MODIFICATION_DATE  DATE,
  BUSINESS_STATUS_DESC    VARCHAR2(100 BYTE),
  IP                      VARCHAR2(30 BYTE),
  IMPFIJO                 NUMBER(20,2),
  COMISION_PORC           NUMBER(3,2),
  MONTO_MIN_COMI          NUMBER(20,2),
  MONTO_MAX_COMI          NUMBER(20,2),
  SUBSTATUS               NUMBER(2),
  AMOUNT_ACTUAL           NUMBER(20,2),
  COMISION_COBRADA        NUMBER(20,2),
  MENSAJEERROR            VARCHAR2(255 BYTE),
  IS_LOADED_FROM_STG      VARCHAR2(1 BYTE),
  ID_NUM_REQUEST          VARCHAR2(58 BYTE),
  REFERENCE_NUMBER_LOTE   NUMBER(16),
  CERTIFY_COMMENT         VARCHAR2(255 BYTE),
  REPROCES_COMMENT        VARCHAR2(255 BYTE),
  DATE_SEND_HOST          TIMESTAMP(6),
  DATE_RESPONSE_HOST      TIMESTAMP(6)
)
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
LOGGING
NOCOMPRESS
NOCACHE
-- Partición por rango mensual sobre DATE_VALUE
PARTITION BY RANGE (DATE_VALUE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION TORDEN_HIST_INICIAL VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD'))
);

-- Comentarios (copiados del original)
COMMENT ON COLUMN PCP.TORDEN_HIST.CUSTOMER_DESCRIPTION IS 'Razon social de la empresa ordenante';
COMMENT ON COLUMN PCP.TORDEN_HIST.ACCOUNT_NUMBER IS 'Numero de cuenta del ordenante';
COMMENT ON COLUMN PCP.TORDEN_HIST.DATE_VALUE IS 'Fecha valor de la orden';
COMMENT ON COLUMN PCP.TORDEN_HIST.TOTAL_AMOUNT IS 'Monto Total de la Orden';
COMMENT ON COLUMN PCP.TORDEN_HIST.TOTAL_COMISSION IS 'Monto Comision Calculada';
COMMENT ON COLUMN PCP.TORDEN_HIST.CENTRO_OPER IS 'Serial informado en el archivo, default 03291';
COMMENT ON COLUMN PCP.TORDEN_HIST.CUSTOMER_ID IS 'Rif del cliente ordenante';
COMMENT ON COLUMN PCP.TORDEN_HIST.DIG_CUSTOMER_ID IS 'Digito verificador del rif';
COMMENT ON COLUMN PCP.TORDEN_HIST.TOTAL_NUM_RECORD IS 'Número Total de registros detail en la orden';
COMMENT ON COLUMN PCP.TORDEN_HIST.TIPO_NOMINA IS 'T Total: P Parcial';
COMMENT ON COLUMN PCP.TORDEN_HIST.CODIGO_PLAN IS 'Código del plan del cliente desde 100000 TCP, 600000 TDA';
COMMENT ON COLUMN PCP.TORDEN_HIST.FECHA_PROCESO IS 'Fecha de proceso según archivo';
COMMENT ON COLUMN PCP.TORDEN_HIST.HORA_PROCESO IS 'Hora de proceso según archivo';
COMMENT ON COLUMN PCP.TORDEN_HIST.NOM_ARCHIVO IS 'Nom archivo';
COMMENT ON COLUMN PCP.TORDEN_HIST.NUMERO_TICKET IS 'Número del ticket asignado por el canal';
COMMENT ON COLUMN PCP.TORDEN_HIST.NUMERO_ASIGNADO_PAMPA IS 'Número asignado en PAMPA';
COMMENT ON COLUMN PCP.TORDEN_HIST.RECORD_ENTRY_DATE IS 'Fecha de creacion del registro';
COMMENT ON COLUMN PCP.TORDEN_HIST.PRODUCT_TYPE IS 'RECARGA/DEVOLUCI';
COMMENT ON COLUMN PCP.TORDEN_HIST.PRODUCT IS 'TDA,TCP';
COMMENT ON COLUMN PCP.TORDEN_HIST.COD_RETORNO_PAMPA IS '00:TODO OK, 01: PROCESADO';
COMMENT ON COLUMN PCP.TORDEN_HIST.TOTAL_OK IS 'total_registros_detail_ok';
COMMENT ON COLUMN PCP.TORDEN_HIST.TOTAL_REJECTS IS 'Total registros_detail_no ok';
COMMENT ON COLUMN PCP.TORDEN_HIST.TOTAL_AMOUNT_REJECTS IS 'Total Monto Rechazado';
COMMENT ON COLUMN PCP.TORDEN_HIST.DATE_APPROVE IS 'Fecha de aprobación del lote';
COMMENT ON COLUMN PCP.TORDEN_HIST.URI_FILE IS 'Nombre del archivo';
COMMENT ON COLUMN PCP.TORDEN_HIST.IMPFIJO IS 'Importe Fijo Comision por registro';
COMMENT ON COLUMN PCP.TORDEN_HIST.COMISION_PORC IS 'Porcentaje de Comision';
COMMENT ON COLUMN PCP.TORDEN_HIST.MONTO_MIN_COMI IS 'Monto Minimo Comision por Registro';
COMMENT ON COLUMN PCP.TORDEN_HIST.MONTO_MAX_COMI IS 'Monto Maximo Comision por Registro';
COMMENT ON COLUMN PCP.TORDEN_HIST.SUBSTATUS IS 'Status 1: control consulta de saldo: NULL, sin consulta; 0, tiene saldo; 1, no tiene saldo; 2,Falla tecnica/Status 2: Control OPS: 3. En proceso de envio; 4. Falla tecnica; 5, Enviado; 6: Recibido';
COMMENT ON COLUMN PCP.TORDEN_HIST.AMOUNT_ACTUAL IS 'Monto Total procesado ';
COMMENT ON COLUMN PCP.TORDEN_HIST.COMISION_COBRADA IS 'Monto Comision Cobrada';

-- Clave primaria en TABLESPACE INDX
ALTER TABLE PCP.TORDEN_HIST ADD (
  CONSTRAINT PK_TORDEN_HIST PRIMARY KEY (ID_TORDEN)
  USING INDEX TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
  ENABLE VALIDATE
);

-- Índices adicionales (todos en INDX)
CREATE INDEX PCP.TORDEN_HIST_CODIGO_PLAN_IDX ON PCP.TORDEN_HIST (CODIGO_PLAN)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.TORDEN_HIST_CUSTOMER_ID_DATE_VALUE_CLI_IDX ON PCP.TORDEN_HIST (CUSTOMER_ID, DATE_VALUE)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.TORDEN_HIST_CUSTOMER_ID_IDX ON PCP.TORDEN_HIST (CUSTOMER_ID)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.TORDEN_HIST_DATE_VALUE_IDX ON PCP.TORDEN_HIST (DATE_VALUE)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.TORDEN_HIST_NRO_PAMPA_IDX ON PCP.TORDEN_HIST (NUMERO_ASIGNADO_PAMPA)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.TORDEN_HIST_RECORD_ENTRY_CLI_IDX ON PCP.TORDEN_HIST (CUSTOMER_ID, TRUNC("RECORD_ENTRY_DATE"))
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.TORDEN_HIST_RECORD_ENTRY_IDX ON PCP.TORDEN_HIST (TRUNC("RECORD_ENTRY_DATE"))
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;