-- DROP TABLE PCP.TORDEN_ALTA_HIST CASCADE CONSTRAINTS PURGE;

CREATE TABLE PCP.TORDEN_ALTA_HIST
(
  ID_TORDEN               NUMBER(18)  NOT NULL,
  CUSTOMER_DESCRIPTION    VARCHAR2(150 BYTE),
  TOTAL_COMISSION         NUMBER(20,2),
  CUSTOMER_ID             VARCHAR2(20 BYTE),
  DIG_CUSTOMER_ID         NUMBER(1),
  TOTAL_NUM_RECORD        NUMBER(12),
  TIPO_ALTA               VARCHAR2(1 BYTE),
  CODIGO_PLAN             VARCHAR2(8 BYTE),
  FECHA_PROCESO           VARCHAR2(10 BYTE),
  HORA_PROCESO            VARCHAR2(8 BYTE),
  NOM_ARCHIVO             VARCHAR2(255 BYTE),
  REFERENCE_NUMBER_LOTE   NUMBER(16),
  NUMERO_TICKET           VARCHAR2(20 BYTE),
  RECORD_ENTRY_DATE       TIMESTAMP(6)          DEFAULT SYSTIMESTAMP,
  PRODUCT_TYPE            VARCHAR2(8 BYTE),
  PRODUCT                 VARCHAR2(8 BYTE),
  COD_RETORNO_PAMPA       VARCHAR2(2 BYTE),
  STATUS                  NUMBER(2),
  BUSINESS_STATUS_CODE    VARCHAR2(4 BYTE),
  TOTAL_OK                NUMBER(20),
  TOTAL_REJECTS           NUMBER(20),
  DATE_APPROVE            TIMESTAMP(6),
  URI_FILE                VARCHAR2(220 BYTE),
  SIZE_FILE               NUMBER(10),
  SUBCHANNEL              NUMBER(1),
  SENT_DATE               DATE,
  SEND_CHANNEL            NUMBER(2),
  LAST_MODIFICATION_DATE  DATE,
  BUSINESS_STATUS_DESC    VARCHAR2(100 BYTE),
  IP                      VARCHAR2(30 BYTE),
  SUBSTATUS               NUMBER(2),
  COMISION_COBRADA        NUMBER(20,2),
  MENSAJEERROR            VARCHAR2(255 BYTE),
  IS_LOADED_FROM_STG      VARCHAR2(1 BYTE),
  ID_NUM_REQUEST          VARCHAR2(58 BYTE),
  CERTIFY_COMMENT         VARCHAR2(255 BYTE),
  REPROCES_COMMENT        VARCHAR2(255 BYTE),
  DATE_SEND_HOST          TIMESTAMP(6),
  DATE_RESPONSE_HOST      TIMESTAMP(6),
  DATE_RESPONSE_HOST_EMI  TIMESTAMP(6),
  CREATOR                 VARCHAR2(30 BYTE),
  APPROVING               VARCHAR2(30 BYTE),
  FECHA_ALTA              DATE
)
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
LOGGING
NOCOMPRESS
NOCACHE
-- Partición por rango mensual sobre RECORD_ENTRY_DATE (TIMESTAMP)
PARTITION BY RANGE (RECORD_ENTRY_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION TORDEN_ALTA_HIST_INICIAL VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD'))
);

COMMENT ON TABLE PCP.TORDEN_ALTA_HIST IS 'Informacion del header de lotes de altas o emisiones de tarjetas';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.CUSTOMER_DESCRIPTION IS 'Nombre de la Empresa';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.TOTAL_COMISSION IS 'Total Comision cobrada';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.CUSTOMER_ID IS 'Id del Cliente Ordenante';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.DIG_CUSTOMER_ID IS 'Digito del rif del cliente ordenante';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.TOTAL_NUM_RECORD IS 'Total Registros';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.TIPO_ALTA IS 'C/P';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.CODIGO_PLAN IS 'Codigo de plan del cliente';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.FECHA_PROCESO IS 'Fecha proceso en el archivo';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.HORA_PROCESO IS 'Hora proceso en el archivo';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.NOM_ARCHIVO IS 'Nombre del Archivo';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.REFERENCE_NUMBER_LOTE IS 'Referencia del Lote';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.NUMERO_TICKET IS 'Número de ticket canal';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.RECORD_ENTRY_DATE IS 'Fecha de Registro';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.PRODUCT_TYPE IS 'ALTAS';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.PRODUCT IS 'TCP/TDA';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.TOTAL_OK IS 'Total registros ok';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.TOTAL_REJECTS IS 'Total registros rechazados';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.DATE_APPROVE IS 'Fecha de aprobacion';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.URI_FILE IS 'Nombre del Archivo';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.SEND_CHANNEL IS 'Canal de ingreso del archivos';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.IP IS 'Ip del equipo ';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.COMISION_COBRADA IS 'Total Comision cobrada';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.DATE_SEND_HOST IS 'Fecha y hora Envio host';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.DATE_RESPONSE_HOST IS 'Fecha y Hora recepcion host';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.DATE_RESPONSE_HOST_EMI IS 'Fecha y Hora respuesta emision';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.CREATOR IS 'Creador del lote';
COMMENT ON COLUMN PCP.TORDEN_ALTA_HIST.APPROVING IS 'Aprobador del lote';

ALTER TABLE PCP.TORDEN_ALTA_HIST ADD (
  CONSTRAINT PK_TORDEN_ALTA_HIST PRIMARY KEY (ID_TORDEN)
  USING INDEX TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
  ENABLE VALIDATE
);

CREATE INDEX PCP.IDX_CODIGO_PLAN_HIST ON PCP.TORDEN_ALTA_HIST (CODIGO_PLAN)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.IDX_CUSTOMER_ID_HIST ON PCP.TORDEN_ALTA_HIST (CUSTOMER_ID)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.IDX_RECORD_ENTRY_DATE_HIST ON PCP.TORDEN_ALTA_HIST (TRUNC("RECORD_ENTRY_DATE"))
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.IDX_RECORD_ENTRY_DATE_CUSTOMER_ID_HIST ON PCP.TORDEN_ALTA_HIST (CUSTOMER_ID, TRUNC("RECORD_ENTRY_DATE"))
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.IDX_STATUS_HIST ON PCP.TORDEN_ALTA_HIST (STATUS)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

CREATE INDEX PCP.IDX_TORDEN_ALTA_FECHA_ALTA_HIST ON PCP.TORDEN_ALTA_HIST (FECHA_ALTA)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;