-- DROP TABLE PCP.TORDEN_DETAIL_ALTA_HIST CASCADE CONSTRAINTS PURGE;

CREATE TABLE PCP.TORDEN_DETAIL_ALTA_HIST
(
  ID_TORDEN             NUMBER(18)              NOT NULL,
  ID_TDETAIL            NUMBER(18)  NOT NULL,
  RECORD_ENTRY_DATE     TIMESTAMP(6),
  CUSTOMER_ID           VARCHAR2(20 BYTE),
  DIG_CUSTOMER_ID       VARCHAR2(1 BYTE),
  APELLIDO1             VARCHAR2(60 BYTE),
  APELLIDO2             VARCHAR2(60 BYTE),
  NOMBRE                VARCHAR2(60 BYTE),
  PEDIDO                VARCHAR2(10 BYTE),
  FAMILIA               VARCHAR2(8 BYTE),
  CIUDAD                VARCHAR2(20 BYTE),
  ESTADO                VARCHAR2(25 BYTE),
  COD_OFI               VARCHAR2(4 BYTE),
  SEXO                  VARCHAR2(1 BYTE),
  COD_AREA              VARCHAR2(7 BYTE),
  NRO_TELF              VARCHAR2(8 BYTE),
  DESC_TELF             VARCHAR2(10 BYTE),
  FEC_NAC               VARCHAR2(8 BYTE),
  DESC_CUSTOMER         VARCHAR2(60 BYTE),
  CARD_NUMBER           VARCHAR2(20 BYTE),
  FECH_VENCIM           VARCHAR2(6 BYTE),
  STATUS                NUMBER(2),
  BUSINESS_STATUS_CODE  VARCHAR2(8 BYTE),
  BUSINESS_STATUS_DESC  VARCHAR2(100 BYTE),
  COD_MENSAJE_OPS       VARCHAR2(4 BYTE),
  DESC_MENSAJE_OPS      VARCHAR2(100 BYTE),
  CURRENCY              VARCHAR2(4 BYTE)
)
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
LOGGING
NOCOMPRESS
NOCACHE

PARTITION BY RANGE (ID_TDETAIL)
INTERVAL (4000000)
(
  PARTITION TORDEN_DETAIL_ALTA_HIST_INICIAL VALUES LESS THAN (4000000)
    TABLESPACE DATA
    PCTFREE 10 INITRANS 1 MAXTRANS 255
    STORAGE ( INITIAL 8M NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
);

COMMENT ON TABLE PCP.TORDEN_DETAIL_ALTA_HIST IS 'Registros Detalle de Lotes de Altas o Emisión de Tarjetas';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.ID_TORDEN IS 'id del lote';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.ID_TDETAIL IS 'Id unico del registro';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.RECORD_ENTRY_DATE IS 'Fecha y hora del registro';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.CUSTOMER_ID IS 'Ci del cliente a Activar';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.APELLIDO1 IS 'Primer Apellido del cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.APELLIDO2 IS 'Segundo apellido del cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.NOMBRE IS 'Nombre del Cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.CIUDAD IS 'Ciudad donde reside el cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.ESTADO IS 'Estado donde reside el cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.SEXO IS 'Genero del Cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.COD_AREA IS 'Codigo de area del telefono';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.NRO_TELF IS 'Nro de Telefono';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.FEC_NAC IS 'Fecha de Nacimiento';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_ALTA_HIST.CURRENCY IS 'Divisa';

-- Clave primaria compuesta (ID_TDETAIL, ID_TORDEN) en INDX
CREATE UNIQUE INDEX PCP.PK_TORDEN_DETAIL_ALTA_HIST ON PCP.TORDEN_DETAIL_ALTA_HIST (ID_TDETAIL, ID_TORDEN)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

ALTER TABLE PCP.TORDEN_DETAIL_ALTA_HIST ADD (
  CONSTRAINT PK_TORDEN_DETAIL_ALTA_HIST PRIMARY KEY (ID_TDETAIL, ID_TORDEN)
  USING INDEX PCP.PK_TORDEN_DETAIL_ALTA_HIST ENABLE VALIDATE
);

-- Índice para la columna ID_TORDEN (para joins)
CREATE INDEX PCP.IDX_TORDEN_DETAIL_ALTA_HIST_ID_TORDEN ON PCP.TORDEN_DETAIL_ALTA_HIST (ID_TORDEN)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

-- Índice por BUSINESS_STATUS_CODE y STATUS
CREATE INDEX PCP.IDX_BUSINESS_STATUS_CODE_HIST ON PCP.TORDEN_DETAIL_ALTA_HIST (BUSINESS_STATUS_CODE, STATUS)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

-- Clave foránea a TORDEN_ALTA_HIST
ALTER TABLE PCP.TORDEN_DETAIL_ALTA_HIST ADD (
  CONSTRAINT FK_TORDEN_DETAIL_ALTA_HIST 
  FOREIGN KEY (ID_TORDEN) REFERENCES PCP.TORDEN_ALTA_HIST (ID_TORDEN) ENABLE VALIDATE
);