-- DROP TABLE PCP.TORDEN_DETAIL_HIST CASCADE CONSTRAINTS PURGE;

CREATE TABLE PCP.TORDEN_DETAIL_HIST
(
  ID_TORDEN             NUMBER(18),
  ID_TDETAIL            NUMBER(18)  NOT NULL,
  RECORD_ENTRY_DATE     TIMESTAMP(6)            DEFAULT SYSTIMESTAMP,
  CUSTOMER_ID           VARCHAR2(20 BYTE),
  DIG_CUSTOMER_ID       VARCHAR2(1 BYTE),
  CUSTOMER_DESC         VARCHAR2(256 BYTE),
  TRANS_TYPE            VARCHAR2(2 BYTE),
  CARD_NUMBER           VARCHAR2(20 BYTE),
  ACCOUNT_NUMBER        VARCHAR2(20 BYTE),
  AMOUNT                NUMBER(20,2),
  STATUS                NUMBER(2),
  BUSINESS_STATUS_CODE  VARCHAR2(8 BYTE),
  BUSINESS_STATUS_DESC  VARCHAR2(100 BYTE),
  COD_MENSAJE_OPS       VARCHAR2(6 BYTE),
  CURRENCY              VARCHAR2(4 BYTE)        DEFAULT 'VEB',
  DESC_MENSAJE_OPS1     VARCHAR2(100 BYTE),
  DESC_MENSAJE_OPS2     VARCHAR2(100 BYTE),
  DESC_MENSAJE_OPS3     VARCHAR2(100 BYTE)
)
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    ( INITIAL 8M NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
LOGGING
NOCOMPRESS
NOCACHE

PARTITION BY RANGE (ID_TDETAIL)
INTERVAL (4000000)
(
  PARTITION TORDEN_DETAIL_HIST_INICIAL VALUES LESS THAN (4000000)
    TABLESPACE DATA
    PCTFREE 10 INITRANS 1 MAXTRANS 255
    STORAGE ( INITIAL 8M NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
);

COMMENT ON COLUMN PCP.TORDEN_DETAIL_HIST.CUSTOMER_ID IS 'Documento del cliente: Comienza por V,E,P';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_HIST.DIG_CUSTOMER_ID IS 'Digito verificador del documento del cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_HIST.CUSTOMER_DESC IS 'Nombre del Cliente';
COMMENT ON COLUMN PCP.TORDEN_DETAIL_HIST.TRANS_TYPE IS 'RE: Recarga, DE: Devolucion';

-- Clave primaria compuesta (ID_TDETAIL, ID_TORDEN) en INDX
CREATE UNIQUE INDEX PCP.PK_TORDEN_DETAIL_HIST ON PCP.TORDEN_DETAIL_HIST (ID_TDETAIL, ID_TORDEN)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 ) LOGGING;

ALTER TABLE PCP.TORDEN_DETAIL_HIST ADD (
  CONSTRAINT PK_TORDEN_DETAIL_HIST PRIMARY KEY (ID_TDETAIL, ID_TORDEN)
  USING INDEX PCP.PK_TORDEN_DETAIL_HIST ENABLE VALIDATE
);

-- Clave foránea a TORDEN_HIST
ALTER TABLE PCP.TORDEN_DETAIL_HIST ADD (
  CONSTRAINT FK_TORDEN_DETAIL_HIST 
  FOREIGN KEY (ID_TORDEN) REFERENCES PCP.TORDEN_HIST (ID_TORDEN) ENABLE VALIDATE
);