-- Eliminar si existe (para pruebas)
-- DROP TABLE PCP.TRACK_LOTE_HIST CASCADE CONSTRAINTS PURGE;

CREATE TABLE PCP.TRACK_LOTE_HIST
(
  ID_TRACK              NUMBER(18)  NOT NULL,
  ID_LOTE               NUMBER(18)              NOT NULL,
  STATUS                NUMBER(2),
  BUSINESS_STATUS_CODE  VARCHAR2(8 BYTE),
  DESCRIPTION           VARCHAR2(255 BYTE),
  RECORD_ENTRY_DATE     TIMESTAMP(6)            DEFAULT SYSTIMESTAMP,
  PRODUCT               VARCHAR2(8 BYTE),
  PRODUCT_TYPE          VARCHAR2(8 BYTE),
  USUARIO               VARCHAR2(70 BYTE)
)
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
LOGGING
NOCOMPRESS
NOCACHE
-- Partición por RANGO sobre ID_TRACK con intervalo de 4.000.000 (igual que tablas de detalle)
PARTITION BY RANGE (ID_TRACK)
INTERVAL (4000000)
(
  PARTITION TRACK_LOTE_HIST_INICIAL VALUES LESS THAN (4000000)
    TABLESPACE DATA
    PCTFREE 10 INITRANS 1 MAXTRANS 255
    STORAGE ( INITIAL 8M NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
);

-- Comentarios (igual que original)
COMMENT ON COLUMN PCP.TRACK_LOTE_HIST.ID_TRACK IS 'id autogenerado';
COMMENT ON COLUMN PCP.TRACK_LOTE_HIST.ID_LOTE IS 'id unico de lote del sistema';
COMMENT ON COLUMN PCP.TRACK_LOTE_HIST.RECORD_ENTRY_DATE IS 'Fecha y hora de entrada del registro, se genera por default';
COMMENT ON COLUMN PCP.TRACK_LOTE_HIST.PRODUCT IS 'producto, en el caso de recargas: TDA,TCP';
COMMENT ON COLUMN PCP.TRACK_LOTE_HIST.PRODUCT_TYPE IS 'Opcional';
COMMENT ON COLUMN PCP.TRACK_LOTE_HIST.USUARIO IS 'usuario que realizo la accion';

-- Clave primaria en TABLESPACE INDX
ALTER TABLE PCP.TRACK_LOTE_HIST ADD (
  CONSTRAINT PK_TRACK_LOTE_HIST PRIMARY KEY (ID_TRACK)
  USING INDEX TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
  ENABLE VALIDATE
);

-- Índice por ID_LOTE (para búsquedas) en INDX
CREATE INDEX PCP.TRACK_LOTE_HIST_ID_LOTE_IDX ON PCP.TRACK_LOTE_HIST (ID_LOTE)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 )
  LOGGING;