CREATE OR REPLACE PACKAGE PICBDV.PKG_API_TRANSFERENCIA AS 

PROCEDURE GET_SERIALES_BANCARIOS(
    p_tipo_documento_emisor IN VARCHAR2,
    p_tipo_documento_receptor IN VARCHAR2,
    p_siglas IN VARCHAR2,
    p_serial OUT VARCHAR2,
    p_serial_debito OUT VARCHAR2,
    p_serial_credito OUT VARCHAR2,
    p_usuarioBus OUT VARCHAR2,
    p_canal OUT VARCHAR2,
    p_subApiconci OUT VARCHAR2,
    p_nombreApi OUT VARCHAR2,
    p_clase_transferencia OUT VARCHAR2,
    p_cod_ret OUT VARCHAR2,
    p_des_ret OUT VARCHAR2
);

PROCEDURE EXISTE_RIF_MERCHANT_SERV (
    V_APIKey          IN  VARCHAR2,
    V_SIGLAS          IN VARCHAR2,
    V_CUENTAMERCHANT  OUT VARCHAR2,
    V_RIFMERCHANT     OUT VARCHAR2,
    V_TLFMERCHANT     OUT VARCHAR2,
    V_NOMBRE		  OUT VARCHAR2,	 
    V_TIPO_CONTROL    OUT VARCHAR2,
    V_CEDULA_RIF_CONTROL    OUT VARCHAR2,
    V_NUMERO_CUENTA_CONTROL    OUT VARCHAR2, 
    V_ENCONTRADO      OUT INT,
    V_COD_RET  OUT VARCHAR2,
    V_DES_RET OUT VARCHAR2
);

PROCEDURE PR_INSERTAR_TRANSFERENCIA (

  PID_APICONCI       IN  NUMBER,
  PBANCOCLIENTE      IN  VARCHAR2,
  PIDCLIENTE         IN  VARCHAR2,
  PNUMEROCLIENTE     IN  VARCHAR2,
  PIDCOMERCIO        IN  VARCHAR2,
  PNUMEROCOMERCIO    IN  VARCHAR2,
  PCODIGOMONEDA      IN  VARCHAR2,
  PMONTO             IN  NUMBER,
  PESTATUS           IN  VARCHAR2,
  POBS               IN  VARCHAR2,
  PESTADO            IN  VARCHAR2,
  PRESPUESTADCS      IN  VARCHAR2,
  PRESPUESTAMEGASOFT IN  VARCHAR2,  
  PREFERENCIA        IN  VARCHAR2,
  PCTA_ORDENANTE     IN  VARCHAR2,
  PCTA_DESTINO       IN  VARCHAR2,
  PNOTIFICACION      IN  CLOB,
  PURL				 IN  VARCHAR2,
  PHEADER		     IN  VARCHAR2,
  P_API_KEY 		 IN  VARCHAR2, 
  COD_RET            OUT VARCHAR2,
  DE_CODRET          OUT VARCHAR2

  );
  
  PROCEDURE PR_INSERTAR_END_TO_END (
    V_CEDULA_RIF IN VARCHAR2,
    V_END_TO_END IN VARCHAR2,
    V_REFERENCIA IN VARCHAR2,
    V_COD_RET   OUT VARCHAR2,
    V_DE_CODRET OUT VARCHAR2
  
  );

  


END PKG_API_TRANSFERENCIA;
/
