Consulta 31 03 2026

col CTERMINAL format a15
col CSERVIDORAPLICACION format a15
col CUSUARIO format a20
col PARAMETROS format a90
col CDISPOSITIVO format a20
col AGRUPAMIENTO format a15

SELECT * FROM inttegriobdv.tdispositivo WHERE CDISPOSITIVO LIKE 'INACTIVESESSIONS%';



UPDATE INTTEGRIOBDV.TDISPOSITIVO SET PARAMETROS = 'com.fitbank.uci.core.tasks.InactiveSessions#450#Caduca Sesiones Inactivas#1200,PC' WHERE CCANAL='FIT' AND CDISPOSITIVO LIKE 'INACTIVESESSIONS%' AND CTIPOCONTROLADOR='TASK';




**************

col CTERMINAL format a15
col CSERVIDORAPLICACION format a15
col CUSUARIO format a20
col PARAMETROS format a90
col CDISPOSITIVO format a20
col AGRUPAMIENTO format a15

SELECT * FROM inttegriobdv.tdispositivo WHERE CDISPOSITIVO LIKE 'UCIWEB%';
SELECT * FROM inttegriobdv.tdispositivo WHERE CDISPOSITIVO LIKE 'INACTIVESESSIONS%';

UPDATE INTTEGRIOBDV.TDISPOSITIVO SET PARAMETROS = 'com.fitbank.uci.core.tasks.InactiveSessions#450#Caduca Sesiones Inactivas#1200,PC' WHERE CCANAL='FIT' AND CDISPOSITIVO LIKE 'INACTIVESESSIONS%' AND CTIPOCONTROLADOR='TASK';

commit;


******

set linesize 500
col URL format a50
col NOMBRE format a15
SELECT * FROM INTTEGRIOBDV.TSERVIDORAPLICACION;


*****
-- Actualizacion de los UCI --

UPDATE INTTEGRIOBDV.TSERVIDORAPLICACION SET NOMBRE='UCI2', ENLINEA='0', URL='http://XXX:8080YYY/UCI', VERSIONCONTROL=10 WHERE CSERVIDORAPLICACION='UCI2';
UPDATE INTTEGRIOBDV.TSERVIDORAPLICACION SET NOMBRE='UCI3', ENLINEA='0', URL='http://XXX:8080YYY/UCI', VERSIONCONTROL=10 WHERE CSERVIDORAPLICACION='UCI3';
UPDATE INTTEGRIOBDV.TSERVIDORAPLICACION SET NOMBRE='UCI4', ENLINEA='0', URL='http://XXX:8080YYY/UCI', VERSIONCONTROL=10 WHERE CSERVIDORAPLICACION='UCI4';
UPDATE INTTEGRIOBDV.TSERVIDORAPLICACION SET NOMBRE='UCI5', ENLINEA='0', URL='http://XXX:8080YYY/UCI', VERSIONCONTROL=10 WHERE CSERVIDORAPLICACION='UCI5';