  COUNT(1) USERNAME             SERVICE_NAME                   MACHINE
---------- -------------------- ------------------------------ ------------------------------------------------------------
       100 INTTEGRIOBDV         INTTEGP                        deploycore-59bbf76ccb-5whkm
       100 INTTEGRIOBDV         INTTEGP                        deploycore-59bbf76ccb-6bpfm
       100 INTTEGRIOBDV         INTTEGP                        deploycore-59bbf76ccb-hbnf9
       100 INTTEGRIOBDV         INTTEGP                        deploycore-59bbf76ccb-m96gl
       100 INTTEGRIOBDV         INTTEGP                        deploycore-59bbf76ccb-t9hm5
       100 INTTEGRIOBDV         INTTEGP                        deploycore-59bbf76ccb-v4bx6
       100 INTTEGRIOBDV         INTTEGP                        deploycore-59bbf76ccb-xh6s8
        50 INTTEGRIOBDV         INTTEGP                        deploycore-665755fb6b-2gnpk
        50 INTTEGRIOBDV         INTTEGP                        deploycore-665755fb6b-7hbvn
        50 INTTEGRIOBDV         INTTEGP                        deploycore-665755fb6b-j4xb6
        50 INTTEGRIOBDV         INTTEGP                        deploycore-665755fb6b-mcnjl
        50 INTTEGRIOBDV         INTTEGP                        deploycore-665755fb6b-xmmhg
        10 INTTEGRIOBDV         INTTEGP                        deployrest-7544cff64c-628c6
       327 INTTEGRIOBDV         INTTEGP                        deployuci-5ffffdf64-2rhtt
       149 INTTEGRIOBDV         INTTEGP                        deployuci-5ffffdf64-8tn8m
       186 INTTEGRIOBDV         INTTEGP                        deployuci-5ffffdf64-fp6qg
       100 INTTEGRIOBDV         INTTEGP                        deployuci-5ffffdf64-hxkj2
       239 INTTEGRIOBDV         INTTEGP                        deployuci-5ffffdf64-jvd2w
       180 INTTEGRIOBDV         INTTEGP                        deployuci-5ffffdf64-k5qcw
       145 INTTEGRIOBDV         INTTEGP                        deployuci-5ffffdf64-xlzn2
        50 INTTEGRIOBDV         INTTEGP                        deployuci-7967cc9c4f-kn7xg
         6 INTTEGRIOBDV         INTTEGP                        deployweb-677c6cbd48-jhdqw
         6 INTTEGRIOBDV         INTTEGP                        deployweb-677c6cbd48-nmxf4
         6 INTTEGRIOBDV         INTTEGP                        deployweb-677c6cbd48-wjk2c
         6 INTTEGRIOBDV         INTTEGP                        deployweb-677c6cbd48-ws9g5
         6 INTTEGRIOBDV         INTTEGP                        deployweb-9c449789b-l4s9s
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-0
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-1
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-2
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-3
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-4
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-5
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-6
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-batch-7
         1 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-clean-0
         1 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-clean-1
         1 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-clean-2
         1 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-clean-3
         1 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-clean-4
         1 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-clean-5
         1 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-mq-to-rb-clean-6
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-0
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-1
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-10
         5 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-11
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-12
         2 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-13
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-14
         2 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-15
         4 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-16
         4 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-17
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-18
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-19
         2 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-2
         2 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-3
         4 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-4
         2 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-5
         2 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-6
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-7
         4 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-8
         2 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-9
        10 INTTEGRIOBDV         INTTEGP_APP                    coexistencia-reactor-91-0
        10 INTTEGRIOBDV         INTTEGP_APP                    conciliation-0
