
-- Logs y Tablas Transaccionales (Hijas)
TRUNCATE TABLE RORAIMA.COMMISSION_LOGS;
TRUNCATE TABLE RORAIMA.FLUCTUATION_LOGS;
TRUNCATE TABLE RORAIMA.PENALTY_LOGS;
TRUNCATE TABLE RORAIMA.POINT_LOGS;
TRUNCATE TABLE RORAIMA.INSTALLMENTS;
TRUNCATE TABLE RORAIMA.TRANSACTIONS;

-- Configuraciones y Relacionadas
TRUNCATE TABLE RORAIMA.MERCHANT_PLAN_CONFIGS;
TRUNCATE TABLE RORAIMA.MERCHANT_BANK_ACCOUNTS;
TRUNCATE TABLE RORAIMA.MERCHANT_ACCOUNTS;
TRUNCATE TABLE RORAIMA.CASHIERS;
TRUNCATE TABLE RORAIMA.BRANCHES;

-- Tablas Maestras (Padres)
TRUNCATE TABLE RORAIMA.LOANS;
TRUNCATE TABLE RORAIMA.MERCHANTS;
TRUNCATE TABLE RORAIMA.USERS;