-- drop table PCP.CREDITS_CREDITO_INMEDIATO_NEW

CREATE TABLE PCP.CREDITS_CREDITO_INMEDIATO_NEW
(
  ID_CREDITS                NUMBER(18)          NOT NULL,
  ENDTOEND                  VARCHAR2(40 BYTE)   NOT NULL,
  FECHA_REGISTRO            DATE                DEFAULT SYSDATE,
  DESC_RESPUESTA_ENVIO      VARCHAR2(250 BYTE),
  DESC_RESPUESTA_RECEPCION  VARCHAR2(250 BYTE),
  ID_ORDEN                  NUMBER(30),
  FECHA_RECIBIDO            DATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (FECHA_REGISTRO)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION CREDITO_INMEDIATO_inicial VALUES LESS THAN (TO_DATE('01-01-2020', 'DD-MM-YYYY'))
);


CREATE INDEX PCP.CREDITS_CREDITO_INMEDIATO_NEW_N1 ON PCP.CREDITS_CREDITO_INMEDIATO_NEW
(ID_CREDITS)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PCP.CREDITS_CREDITO_INMEDIATO_NEW_N2 ON PCP.CREDITS_CREDITO_INMEDIATO_NEW
(ENDTOEND)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
