-- DROP TABLE PCP.DATOS_MOVIMIENTOS_HIST

CREATE TABLE PCP.DATOS_MOVIMIENTOS_HIST (
  ID_RESPUESTA      NUMBER(18),
  ID_ORDEN          NUMBER(30),
  ID_DEBITO         NUMBER(18),
  ID_COMISION       NUMBER(18),
  ID_CREDITO        NUMBER(18),
  NIO_DEBITO        VARCHAR2(30 BYTE),
  NRO_MOV_DEBITO    VARCHAR2(20 BYTE),
  NIO_COMISION      VARCHAR2(30 BYTE),
  NRO_MOV_COMISION  VARCHAR2(20 BYTE),
  NIO_CREDITO       VARCHAR2(30 BYTE),
  NRO_MOV_CREDITO   VARCHAR2(20 BYTE),
  FECHA_REGISTRO    DATE,
  IS_COMISION       VARCHAR2(1 BYTE),
  APLICA_REVERSO    VARCHAR2(1 BYTE),
  APLICA_ANULACION  VARCHAR2(1 BYTE),
  FECHA_REVER_ANU   DATE
)
PARTITION BY RANGE (FECHA_REGISTRO)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION DATOS_MOVIMIENTOS_HIST_inicial VALUES LESS THAN (TO_DATE('2018-01-01', 'YYYY-MM-DD'))
);