--DROP TABLE PCP.CREDITS_HIST CASCADE CONSTRAINTS;

CREATE TABLE PCP.CREDITS_HIST
(
  ID_CREDITS              NUMBER,
  ID_DEBITS               NUMBER,
  RECORD_ENTRY_DATE       DATE,
  REFERENCE_NUMBER        VARCHAR2(50 BYTE),
  CUSTOMER_ID             VARCHAR2(50 BYTE),
  CUSTOMER_DESC           VARCHAR2(256 BYTE),
  PROCESS_DATE            DATE,
  ACCOUNT_NUMBER          VARCHAR2(50 BYTE),
  ACCOUNT_TYPE            VARCHAR2(20 BYTE),
  AMOUNT                  NUMBER,
  PAYMENT_TYPE            VARCHAR2(20 BYTE),
  EMAIL                   VARCHAR2(200 BYTE),
  STATUS                  VARCHAR2(20 BYTE),
  IS_DOMICILIATION        VARCHAR2(1 BYTE),
  BUSINESS_STATUS_CODE    VARCHAR2(50 BYTE),
  CUSTOMER_ID_OPS         VARCHAR2(50 BYTE),
  ID_ORDEN                NUMBER,
  BUSINESS_STATUS_DESC    VARCHAR2(200 BYTE),
  STATUS_OPS_CCE          VARCHAR2(50 BYTE),
  COMISION_TRANSPORTISTA  NUMBER,
  SITE_CODE_CREDITOR      VARCHAR2(50 BYTE),
  COD_MENSAJE_OPS         VARCHAR2(50 BYTE),
  DIG_CUSTOMER_ID         VARCHAR2(50 BYTE),
  STATUS_OPS_BCV          VARCHAR2(50 BYTE),
  MOVED_DATE              DATE
)
NOCOMPRESS 
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (PROCESS_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(  
  PARTITION P_INITIAL VALUES LESS THAN (TO_DATE(' 2018-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE;
