-- DROP TABLE LOGS_RESP_PROC_PCP1_HIST

CREATE TABLE LOGS_RESP_PROC_PCP1_HIST (
  ID_DATOS_RES    NUMBER(18),
  ID_ORDEN        NUMBER(30),
  ID_DEBITO       NUMBER(18),
  ID_COMISION     NUMBER(18),
  ID_CREDITO      NUMBER(18),
  COD_RESP        VARCHAR2(30 BYTE),
  DESCRIPCION     VARCHAR2(2000 BYTE),
  FECHA_REGISTRO  DATE
)
PARTITION BY RANGE (FECHA_REGISTRO)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION LOGS_RESP_PROC_PCP1_HIST_inicial VALUES LESS THAN (TO_DATE('2018-01-01', 'YYYY-MM-DD'))
);