-- DROP TABLE CREDITS_CREDITO_INMEDIATO_HIST

CREATE TABLE CREDITS_CREDITO_INMEDIATO_HIST (
  ID_CREDITS                NUMBER(18)          NOT NULL,
  ENDTOEND                  VARCHAR2(40 BYTE),
  FECHA_REGISTRO            DATE,
  DESC_RESPUESTA_ENVIO      VARCHAR2(250 BYTE),
  DESC_RESPUESTA_RECEPCION  VARCHAR2(250 BYTE),
  ID_ORDEN                  NUMBER(30),
  FECHA_RECIBIDO            DATE
)
PARTITION BY RANGE (FECHA_REGISTRO)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION CREDITO_INMEDIATO_HIST_inicial VALUES LESS THAN (TO_DATE('2018-01-01', 'YYYY-MM-DD'))
);