--DROP TABLE PCPH.TRACK_ORDEN_HIST CASCADE CONSTRAINTS;

CREATE TABLE PCPH.TRACK_ORDEN_HIST
(
  ID_TRACK_ORDEN        NUMBER(18)              NOT NULL,
  ID_ORDEN              VARCHAR2(50 BYTE),
  STATUS                NUMBER(2),
  BUSINESS_STATUS_CODE  VARCHAR2(8 BYTE),
  DESCRIPTION           VARCHAR2(255 BYTE),
  RECORD_ENTRY_DATE     DATE,
  PAYMENT_TYPE          VARCHAR2(3 BYTE),
  USUARIO               VARCHAR2(70 BYTE),
  TIPO_PAGO             VARCHAR2(2 BYTE),
  DESC_TIPO_PAGO        VARCHAR2(40 BYTE)
)
NOCOMPRESS 
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (ID_TRACK_ORDEN)
INTERVAL (100000) (
    PARTITION TRACK_ORDEN_inicial VALUES LESS THAN (100001)
);

