-- DROP TABLE CREDITS_NEW
CREATE TABLE PCP.CREDITS_NEW
(
  ID_CREDITS              NUMBER(18)            NOT NULL,
  ID_DEBITS               NUMBER(18)            NOT NULL,
  RECORD_ENTRY_DATE       DATE                  DEFAULT SYSDATE,
  REFERENCE_NUMBER        NUMBER(20),
  CUSTOMER_ID             VARCHAR2(20 BYTE),
  CUSTOMER_DESC           VARCHAR2(256 BYTE),
  PROCESS_DATE            DATE,
  ACCOUNT_NUMBER          VARCHAR2(20 BYTE),
  ACCOUNT_TYPE            VARCHAR2(3 BYTE),
  AMOUNT                  NUMBER(20,2),
  PAYMENT_TYPE            VARCHAR2(3 BYTE),
  EMAIL                   VARCHAR2(50 BYTE),
  STATUS                  NUMBER(2)             DEFAULT 0,
  IS_DOMICILIATION        VARCHAR2(1 BYTE),
  BUSINESS_STATUS_CODE    VARCHAR2(8 BYTE),
  CUSTOMER_ID_OPS         VARCHAR2(20 BYTE),
  ID_ORDEN                NUMBER(18),
  BUSINESS_STATUS_DESC    VARCHAR2(100 BYTE),
  STATUS_OPS_CCE          NUMBER(2),
  COMISION_TRANSPORTISTA  NUMBER(2),
  SITE_CODE_CREDITOR      VARCHAR2(12 BYTE),
  COD_MENSAJE_OPS         VARCHAR2(6 BYTE),
  DIG_CUSTOMER_ID         VARCHAR2(1 BYTE),
  STATUS_OPS_BCV          NUMBER(2)
)
NOCOMPRESS
TABLESPACE DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (ID_CREDITS)
INTERVAL (10000000)
(
  PARTITION CREDITS_INICIAL VALUES LESS THAN (10000001)
    LOGGING
    NOCOMPRESS
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE;

-- Comentarios de columna (conservados del original)
COMMENT ON COLUMN PCP.CREDITS_NEW.BUSINESS_STATUS_DESC IS 'la respuesta de host o de cce';
COMMENT ON COLUMN PCP.CREDITS_NEW.STATUS_OPS_CCE IS 'se refiere al estatus del envio de los debitos a cce cuenta 989';

-- Índices globales (no dependen del particionamiento)
CREATE INDEX PCP.CREDITS_NEW_N1 ON PCP.CREDITS_NEW (COMISION_TRANSPORTISTA)
  LOGGING TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT);

CREATE INDEX PCP.CREDITS_NEW_N2 ON PCP.CREDITS_NEW (ID_ORDEN)
  NOLOGGING TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT);

CREATE INDEX PCP.CREDITS_NEW_N3 ON PCP.CREDITS_NEW (PROCESS_DATE)
  NOLOGGING TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT);

CREATE INDEX PCP.CREDITS_NEW_N4 ON PCP.CREDITS_NEW (ID_CREDITS, PROCESS_DATE)
  NOLOGGING TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT);

CREATE INDEX PCP.CREDITS_NEW_N5 ON PCP.CREDITS_NEW (ID_DEBITS)
  LOGGING TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT);

-- Índices locales: se crean como LOCAL sin enumerar particiones (Oracle las crea automáticamente)
CREATE INDEX PCP.CREDITS_NEW_N6 ON PCP.CREDITS_NEW (BUSINESS_STATUS_CODE)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (BUFFER_POOL DEFAULT) NOLOGGING LOCAL;

CREATE INDEX PCP.CREDITS_NEW_N7 ON PCP.CREDITS_NEW (STATUS, ID_CREDITS)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (BUFFER_POOL DEFAULT) NOLOGGING LOCAL;

CREATE INDEX PCP.CREDITS_NEW_N8 ON PCP.CREDITS_NEW (ID_DEBITS, ID_CREDITS)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (BUFFER_POOL DEFAULT) NOLOGGING LOCAL;

CREATE INDEX PCP.CREDITS_NEW_N9 ON PCP.CREDITS_NEW (STATUS, BUSINESS_STATUS_CODE)
  TABLESPACE INDX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (BUFFER_POOL DEFAULT) NOLOGGING LOCAL;

-- Clave foránea
ALTER TABLE PCP.CREDITS_NEW ADD (
  CONSTRAINT FK_DEBITS_IIII
  FOREIGN KEY (ID_DEBITS)
  REFERENCES PCP.DEBITS (ID_DEBITS)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);