spool CREACION_ESQUEMA_RORAIMA.LOG


prompt CREATE TABLESPACE DATA_RORAIMA DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;
CREATE TABLESPACE DATA_RORAIMA DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;

prompt CREATE TABLESPACE INDEX_RORAIMA DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;
CREATE TABLESPACE INDEX_RORAIMA DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;

prompt CREATE TABLESPACE DATA_RORAIMA_AUDIT DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;
CREATE TABLESPACE DATA_RORAIMA_AUDIT DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;

prompt CREATE TABLESPACE INDEX_RORAIMA_AUDIT DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;
CREATE TABLESPACE INDEX_RORAIMA_AUDIT DATAFILE SIZE 30G AUTOEXTEND ON NEXT 2048M MAXSIZE UNLIMITED;


prompt CREATE PROFILE APP LIMIT 
CREATE PROFILE APP LIMIT 
	COMPOSITE_LIMIT                  UNLIMITED
	SESSIONS_PER_USER                UNLIMITED
	CPU_PER_SESSION                  UNLIMITED
	CPU_PER_CALL                     UNLIMITED
	LOGICAL_READS_PER_SESSION        UNLIMITED
	LOGICAL_READS_PER_CALL           UNLIMITED
	IDLE_TIME                        UNLIMITED
	CONNECT_TIME                     UNLIMITED
	PRIVATE_SGA                      UNLIMITED
	FAILED_LOGIN_ATTEMPTS            UNLIMITED
	PASSWORD_LIFE_TIME               UNLIMITED
	PASSWORD_REUSE_TIME              UNLIMITED
	PASSWORD_REUSE_MAX               UNLIMITED
	PASSWORD_VERIFY_FUNCTION         NULL
	PASSWORD_LOCK_TIME               UNLIMITED
	PASSWORD_GRACE_TIME              UNLIMITED
	INACTIVE_ACCOUNT_TIME			 DEFAULT;


prompt CREATE ROLE APP_RORAIMA;
CREATE ROLE APP_RORAIMA;

prompt GRANT CREATE SESSION
GRANT CREATE SESSION
, CREATE VIEW
, CREATE MATERIALIZED VIEW
, CREATE PROCEDURE
, CREATE TRIGGER
, CREATE TABLE
, CREATE SEQUENCE
, CREATE SYNONYM 
, EXECUTE TO APP_RORAIMA;


prompt CREATE USER RORAIMA 
CREATE USER RORAIMA 
IDENTIFIED BY "RORAIMA2026"
PROFILE APP
DEFAULT TABLESPACE DATA_RORAIMA
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;


prompt CREATE USER RORAIMA_AUDITORIA
CREATE USER RORAIMA_AUDITORIA
IDENTIFIED BY "RORAIMA2026"
PROFILE APP
DEFAULT TABLESPACE DATA_RORAIMA
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;




prompt GRANT APP_RORAIMA TO RORAIMA_AUDITORIA;
GRANT APP_RORAIMA TO RORAIMA_AUDITORIA;

prompt GRANT APP_RORAIMA TO RORAIMA;
GRANT APP_RORAIMA TO RORAIMA;


prompt GRANT CONNECT, CREATE SESSION TO RORAIMA_AUDITORIA;
GRANT CONNECT, CREATE SESSION TO RORAIMA_AUDITORIA;

prompt GRANT CONNECT, CREATE SESSION TO RORAIMA;
GRANT CONNECT, CREATE SESSION TO RORAIMA;




prompt ALTER USER RORAIMA QUOTA UNLIMITED ON DATA_RORAIMA;
ALTER USER RORAIMA QUOTA UNLIMITED ON DATA_RORAIMA;
prompt ALTER USER RORAIMA QUOTA UNLIMITED ON INDEX_RORAIMA;
ALTER USER RORAIMA QUOTA UNLIMITED ON INDEX_RORAIMA;
prompt ALTER USER RORAIMA_AUDITORIA QUOTA UNLIMITED ON DATA_RORAIMA_AUDIT;
ALTER USER RORAIMA_AUDITORIA QUOTA UNLIMITED ON DATA_RORAIMA_AUDIT;
prompt ALTER USER RORAIMA_AUDITORIA QUOTA UNLIMITED ON INDEX_RORAIMA_AUDIT;
ALTER USER RORAIMA_AUDITORIA QUOTA UNLIMITED ON INDEX_RORAIMA_AUDIT;

spool off
